steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/gcp-final-task-project/epam-final-task-project-artifact-registry-repo/java-app:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/gcp-final-task-project/epam-final-task-project-artifact-registry-repo/java-app:$SHORT_SHA']
#  - name: 'gcr.io/cloud-builders/kubectl'
#    args: ['set', 'image', 'deployment/java-app', 'java-app=europe-west1-docker.pkg.dev/gcp-final-task-project/epam-final-task-project-artifact-registry-repo/java-app:$SHORT_SHA']
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=epam-final-task-cluster'
images: ['europe-west1-docker.pkg.dev/gcp-final-task-project/epam-final-task-project-artifact-registry-repo/java-app:$SHORT_SHA']
