spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: gcp_final_task
  flyway:
    driver-class-name: org.postgresql.Driver
    enabled: true
    default-schema: gcp_final_task
