spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=yourcurrentSchema
    username: postgres
    password: postgres

  jpa:
    hibernate:
      default_schema: yourcurrentSchema
      ddl-auto: validate
      show-sql: true
  flyway:
    driver-class-name: org.postgresql.Driver
    enabled: true
