apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-app
  name: java-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/gcp-final-task-project/epam-final-task-project-artifact-registry-repo/java-app:v0.1
          imagePullPolicy: IfNotPresent
          name: java-app
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: java-app
  name: java-app
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  ports:
    - nodePort: 32648
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-app
  sessionAffinity: None
  type: LoadBalancer
