apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-app
  name: java-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-app
    spec:
      serviceAccountName: 'cloudsql-ksa'
      containers:
        - image: '{{IMAGE}}'
          imagePullPolicy: IfNotPresent
          name: java-app
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gcp-final-task-db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gcp-final-task-db-secret
                  key: password
        - name: 'java-app-db-proxy'
          image: 'gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1'
          imagePullPolicy: IfNotPresent
          args:
            - '--quiet'
            - '--private-ip'
            - '--port=5432'
            - 'gcp-final-task-project:europe-west1:gcp-final-task-project-db'
