apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-app
  name: java-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - image: '{{IMAGE}}'
          imagePullPolicy: IfNotPresent
          name: java-app
          ports:
            - containerPort: 8080
              protocol: TCP
