apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-app-dev
  name: java-app-dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80 # 8080
  selector:
    app: java-app-dev
    role: backend-service
    env: dev
  sessionAffinity: None
  type: LoadBalancer